services:
    reverse-proxy:
      image: traefik:v3.1
      ports:
        - "80:80"
        - "8080:8080"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./traefik/traefik.yml:/traefik.yml:ro
      restart: unless-stopped
      environment:
        TZ: Europe/Moscow
      networks:
        - bitrixdock

    php:
        build: ./php/${PHP_VERSION}
        volumes:
            - ${SITE_PATH}:/var/www/bitrix
            - /etc/localtime:/etc/localtime/:ro
        environment:
            TZ: Europe/Moscow
        networks:
            - bitrixdock
        restart: unless-stopped

    web_server:
        build: ./${WEB_SERVER_TYPE}
        volumes:
            - ${SITE_PATH}:/var/www/bitrix
            - /etc/localtime:/etc/localtime/:ro
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${SITE_DOMAIN}`)"
          - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"
        networks:
            - bitrixdock
        environment:
            TZ: Europe/Moscow
        restart: unless-stopped

    db:
        build: ./${DB_SERVER_TYPE}
        volumes:
            - ./${DB_SERVER_TYPE}/init:/docker-entrypoint-initdb.d
            - /etc/localtime:/etc/localtime/:ro
            - db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            TZ: Europe/Moscow
        networks:
            - bitrixdock
        restart: unless-stopped

    adminer:
        image: dockette/adminer:full
        environment:
            UPLOAD: 1024M # upload_max_filesize, post_max_size
            TZ: Europe/Moscow
        restart: unless-stopped
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.adminer_${COMPOSE_PROJECT_NAME}.rule=Host(`adminer.${SITE_DOMAIN}`)"
          - "traefik.http.services.adminer_${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"
        networks:
            - bitrixdock

volumes:
    db:
        driver: local

networks:
    bitrixdock:
      driver: bridge
